### ISSUE TITLE
[Bug]Getting unwanted mp4 file format with no audio

### ISSUE THREAD

**Issue by shremoes** [nandyalu/trailarr#37]
**Describe the bug**
Several Movies in my library end up with a .mp4 trailer downloaded even though MKV file format is specified in the settings. The MKV files work fine. However, ALL of the mp4 trailers that are downloaded into my library are missing the audio track.

**Steps To Reproduce**
1. Go to settings in the backend
2. Click on the Trailers Tab
3. Change Trailer File Format to MKV. Trailer Video Format: h264. Trailer Audio Format: eac3
4. Trailers are downloaded to the movie library. Random movies get .mp4 trailer extensions with no audio track.

**Actual behavior**
Trailers are downloaded for each movie in the library, some download with the mkv file format and work fine. Some download with mp4 file format with no audio track.

**Expected behavior**
Trailers are downloaded and converted to mkv file format as specified in the settings.

**Screenshots**
![missing_audio_track](https://github.com/user-attachments/assets/4ce1b449-75ce-441c-88ae-8ad836fbb8dd)
![vlc_missing_audio_track](https://github.com/user-attachments/assets/661540c8-63c4-46ed-a301-34265dd23ac1)
![folder_structure](https://github.com/user-attachments/assets/35a62ab3-978c-4621-8ab7-8497c1edbe5b)

**App Information (please complete the following information):**
- Installed in Unraid 6.12.13 using the latest branch in the repository

**Additional context**
I have a very large collections that is hard to track down all that are incorrect. I cannot figure out the common denominator for those that do not get converted to the correct format.
The screenshot shows an example movie. If more movie examples are needed I can provide them. Deleting the trailers and downloading them again through the backend ended with the same result, mp4 format with no audio track.

**Comment by dannyvassallo** [comment]
I have this same problem but its captured webm files. I see the linked fix - any timeline on when the new image will be available on unraid? or do you not manage those releases?

Additionally, does this handle cleanup of the illegitimate files? I've had to stop using this app because of this and the changes still aren't present in the image for the unraid releases and I'm continuing to get thousands of trailers that don't have sound.

**Comment by nandyalu** [comment]
This fix is not released yet, I am planning on releasing this soon (either this week or next). There are some other things that are going live with the next release like the ability to see all your media in the app (when you open in browser).

This update will not handle cleanup of trailers without audio, there are a few reasons for that:
1. App also checks if a trailer was already downloaded and exists in the media folder, so app won't be able to differentiate between trailers downloaded by this app or something else.
2. Since the trailers with missing audio are incorrect, app did not set the correct file permissions for those, so it won't be able to delete them.

That being said, I will see if I can add something to check if trailers are missing audio streams in them and maybe display those problematic file paths in logs, so that you can delete them manually (or if it's possible to delete them with the app itself).

Unraid template: Yes, I am not maintaining the unraid template @jpdvm2014 maintains that.

**Comment by dannyvassallo** [comment]
Possible feature request: Allow cleanup of old trailers as a toggle / checkbox? I've never used anything but this to aggregate trailers and now I have a bit of a mess on my hands.

**Comment by JPDVM2014** [comment]
The unraid template should pull the newest image available whenever you update as long as you didn't manually specific a version.
