### ISSUE TITLE
[Bug] Unable to have Trailers saved alongside content in respective folders

### ISSUE THREAD

**Issue by Andrewpaps** [nandyalu/trailarr#38]
**Describe the bug**

The current behaviour is saving the trailers in a folder named media within Trailarr's own appdata folder, but I want it saved next to it's respective content in order for automatic discovery within Plex.

Currently, there does not seem to be a way to configure this either in container settings or within the app itself unless I have missed something.

**Comment by nandyalu** [comment]
There could be something wrong with your setup. Did you check the docs regarding [Volume Mapping](https://nandyalu.github.io/trailarr/install/volume-mapping/)?

**Comment by Andrewpaps** [comment]
I believe so. This is how it is currently set.

![image](https://github.com/user-attachments/assets/2c5adcb0-f563-4b90-a1aa-714381b1882b)

**Comment by Andrewpaps** [comment]
For reference, in Radarr for example they are mapped like so:

![image](https://github.com/user-attachments/assets/6cc59f26-99c4-4952-be04-79e6049ad507)

**Comment by nandyalu** [comment]
You have to update your volume mappings, and might also need to add path mappings. Can you post your Radarr and Sonarr templates?

**Comment by Andrewpaps** [comment]
Sure. For reference, "/data" is what I map to externally as that top directory is referenced by multiple other containers.

I did see that the container uses "/data" internally instead of the standard "/config", not sure if something is going on with that.

![image](https://github.com/user-attachments/assets/3b1cb0a2-0aeb-45b7-8992-a2328517105b)

![image](https://github.com/user-attachments/assets/ae29bb54-dcef-420e-bfa6-ddc19a7b08f5)

**Comment by nandyalu** [comment]
@Andrewpaps you need a few changes to your config.

1. Trailarr has an environment variable `APP_DATA_DIR`, set it to `/config`. This will make the app use `/config` folder internally for storing app data.
2. Edit the `APPDATA` to container path to `/config`.
3. Since both your Radarr and Sonarr media folders are mapped to `/data` within their containers, you need to do the same with Trailarr. Modify the `Radarr Path` to change path to `/mnt/user/data` and container path to `/data`.
4. Now, since Sonarr media folder is also in the same internal path as Radarr, you can remove `Sonarr path` from template.
5. Save the changes and start the container.

Make these changes and see if it works!

**Comment by Andrewpaps** [comment]
Yes! That has worked.

Apologies, I believe I was getting confused by some of the terminology in the default template, as it is usually used differently i.e. /data being used for /config and also the Radarr/Sonarr root folder it asks for being the media folder, not their appdata.

For anyone finding themselves with a similar issue, the working template is:

![image](https://github.com/user-attachments/assets/edbbd182-37a7-42c5-b269-7cce5220a635)

**Comment by nandyalu** [comment]
@Andrewpaps this will help others if anyone is in a similar situation. I also updated the app to use `/config` folder for storing app data as default (as part of next release).

Trailarr was an app I developed and used for myself initially and since it was working well for me, I thought I'll share it for others who wants to use it. So, I had app data saving to `/data` folder and it worked for me, but it might not be the case for everyone so the changes!
