### ISSUE TITLE
[Bug] Case-sensitive search

### ISSUE THREAD

**Issue by DenisSolonevich** [nandyalu/trailarr#46]
It looks like the search is case-sensitive. Could you check it please for sure?

**Comment by nandyalu** [comment]
search in youtube? or search in Trailarr app search bar?

**Comment by DenisSolonevich** [comment]
Search in Trailarr.
E.g. 
Harry Potter - OK
harry potter - Nothing Found

**Comment by nandyalu** [comment]
It's working for me with lower case too...

![Screenshot_20240928_154828_Samsung Internet.jpg](https://github.com/user-attachments/assets/11297008-55f4-48f7-b59e-55992cfdcb91)

Can you post a screenshot if possible?

**Comment by DenisSolonevich** [comment]
You're right. I made more tests. It is case-sensitive for non-english (russian) language only.
Could you please check it on the code-level?

<img width="489" alt="eng" src="https://github.com/user-attachments/assets/d77770b1-83d7-4ca6-915c-0c2bf1111cff">
<img width="489" alt="ru_fail" src="https://github.com/user-attachments/assets/247e7daa-7407-454d-9cc2-6d03074c8772">
<img width="489" alt="ru_success" src="https://github.com/user-attachments/assets/e8df52d7-e48d-4df3-afaf-061699c1cd82">

**Comment by nandyalu** [comment]
@DenisSolonevich I have looked into this and it seems like a problem with `sqlite database` itself.

> Important Note: SQLite only understands upper/lower case for ASCII characters by default. The LIKE operator is case sensitive by default for unicode characters that are beyond the ASCII range. For example, the expression 'a' LIKE 'A' is TRUE but 'æ' LIKE 'Æ' is FALSE. The ICU extension to SQLite includes an enhanced version of the LIKE operator that does case folding across all unicode characters.

Source: https://www.sqlite.org/lang_expr.html#the_like_glob_regexp_and_match_operators

There are some workarounds that can be implemented but it will come with performance degradation (takes more time to perform the search). Since the risks outweighs the benefits, we will not implement them at this time.
